var path = require('path'),
    fs = require('fs');

var myArgs = process.argv.slice(2),
    scArgs = process.argv.slice(0,2);
    srcPath = myArgs[0] + "/Packages/QROS/amd/qros-definitions.js";
    destPath = myArgs[1] + "/web/autogenerated/qros/qmc-qros-definitions.js";
    
    if (myArgs.length !== 2) {
        console.log("Usage: qroscopy source-project destination-project");
        process.exit();
    }
    
    console.log('From: ', path.resolve( srcPath ));
    console.log('To  : ', path.resolve( destPath ));
    
        
copyFile( path.resolve( srcPath ), path.resolve( destPath ), cb); 

function copyFile(source, target, cb) {
  var cbCalled = false;

  var rd = fs.createReadStream(source);
  rd.on("error", function(err) {
    done(err);
  });
  var wr = fs.createWriteStream(target);
  wr.on("error", function(err) {
    done(err);
  });
  wr.on("close", function(ex) {
    done("Sucessfully copied the file");
  });
  rd.pipe(wr);

  function done(err) {
    if (!cbCalled) {
      cb(err);
      cbCalled = true;
    }
  }
}

function cb(msg) {
    if (msg){
        console.log(msg);
    }
}
 